name: Try push to owner repo

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout owner repo
        uses: actions/checkout@v4
        with:
          repository: OWNER_ORG/owner-repo
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Try commit
        run: |
          echo "test" > action-fail.txt
          git add .
          git commit -m "action test"
          git push
